// rf_shadergen.cpp - BUILD-TIME tool: compiles the post-pass variants (SharpenHlsl.h + nis/NIS_Scaler.h) to DXBC
// cs_5_0 with the exact D3DCompile call the shim used to make on Unity's render thread, and writes them as byte
// arrays into the header named on the command line (CMake: sharpen_dxbc.h). Exit != 0 on any compile/write failure,
// which fails the build - a broken shader can never ship.
#include <windows.h>
#include <d3dcompiler.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>

#include "SharpenHlsl.h"
#include "nis_scaler_hlsl.h"    // generated by CMake from nis/NIS_Scaler.h: kNisScalerHlsl[] (NUL-terminated)

static ID3DBlob* Compile(const std::string& src, const char* name)
{
    ID3DBlob* code = NULL; ID3DBlob* err = NULL;
    HRESULT hr = D3DCompile(src.data(), src.size(), name, NULL, NULL, "main", "cs_5_0", D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, &code, &err);
    if (FAILED(hr) || !code) {
        fprintf(stderr, "rf_shadergen: %s failed hr=0x%08X\n%s\n", name, (unsigned)hr, err ? (const char*)err->GetBufferPointer() : "");
        if (err) err->Release();
        if (code) code->Release();
        return NULL;
    }
    if (err) err->Release();
    return code;
}

static std::string NisSource(bool hdr)
{
    std::string s = hdr ? "#define NIS_HDR_MODE 1\n" : "#define NIS_HDR_MODE 0\n";
    s += kNisPreamble;
    s += (const char*)kNisScalerHlsl;
    s += kNisMain;
    return s;
}

static bool Emit(FILE* f, const char* array, ID3DBlob* blob)
{
    if (!blob) return false;
    const unsigned char* p = (const unsigned char*)blob->GetBufferPointer();
    size_t n = blob->GetBufferSize();
    fprintf(f, "static const unsigned char %s[%u] = {", array, (unsigned)n);
    for (size_t i = 0; i < n; ++i) fprintf(f, "%s0x%02x,", (i % 24) ? "" : "\n", p[i]);
    fprintf(f, "\n};\n");
    blob->Release();
    return true;
}

int main(int argc, char** argv)
{
    if (argc != 2) { fprintf(stderr, "usage: rf_shadergen <out.h>\n"); return 2; }
    ID3DBlob* nisLdr = Compile(NisSource(false), "nis_sharpen");
    ID3DBlob* nisHdr = Compile(NisSource(true), "nis_sharpen");
    ID3DBlob* grade = Compile(std::string(kColorGradeHlsl, sizeof(kColorGradeHlsl) - 1), "analytic_color_grade");
    if (!nisLdr || !nisHdr || !grade) {
        if (nisLdr) nisLdr->Release(); if (nisHdr) nisHdr->Release(); if (grade) grade->Release();
        return 1;
    }
    std::string tmp = std::string(argv[1]) + ".tmp";
    FILE* f = NULL;
    if (fopen_s(&f, tmp.c_str(), "wb") != 0 || !f) { fprintf(stderr, "rf_shadergen: cannot write %s\n", tmp.c_str()); return 1; }
    fprintf(f, "// generated by rf_shadergen from SharpenHlsl.h + nis/NIS_Scaler.h - DXBC cs_5_0, do not edit\n#pragma once\n");
    bool ok = Emit(f, "kCsNisLdr", nisLdr) && Emit(f, "kCsNisHdr", nisHdr) && Emit(f, "kCsGrade", grade);
    ok = fclose(f) == 0 && ok;
    // Replace atomically so an interrupted run never leaves a half header that still compiles.
    if (!ok || !MoveFileExA(tmp.c_str(), argv[1], MOVEFILE_REPLACE_EXISTING)) {
        fprintf(stderr, "rf_shadergen: writing %s failed\n", argv[1]);
        DeleteFileA(tmp.c_str());
        return 1;
    }
    return 0;
}
