// DlssNative.cpp - NGX D3D11 DLSS shim. Plain C style, one static state block, no threads, no exceptions.
#define DLSSNATIVE_EXPORTS
#include "DlssNative.h"

#include <d3d11.h>
#include <d3dcompiler.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

#include "nvsdk_ngx.h"
#include "nvsdk_ngx_helpers.h"
#include "nis/NIS_Config.h"     // NVIDIA Image Scaling SDK 1.0.3 (MIT): NISConfig + NVSharpenUpdateConfig
#include "nis_scaler_hlsl.h"    // generated by CMake from nis/NIS_Scaler.h: kNisScalerHlsl[] (NUL-terminated)

static const char* kProjectId = "b7a3f2c4-6d1e-4a8b-9c0f-2e5d7a9b1c3d";
static const char* kEngineVersion = "2019.4.31";

static struct {
    int initCode;                 // last Dlss_Init code, DLSS_ERR_NO_DEVICE until init ran
    int ngxInitialized;
    ID3D11Device* device;
    NVSDK_NGX_Parameter* params;  // capability params, reused for create/eval
    NVSDK_NGX_Handle* feature;
    NVSDK_NGX_Result lastCreate, lastEval;
    int needsDriver;
    unsigned minDriverMajor, minDriverMinor;
    wchar_t dllDir[MAX_PATH];

    NVSDK_NGX_DLSS_Create_Params create;
    int quality;
    // Ring of per-frame blocks: main thread fills slot N while the render thread may still read slot N-1..N-3.
    NVSDK_NGX_D3D11_DLSS_Eval_Params slots[4];
    unsigned slotIdx;
    NVSDK_NGX_D3D11_DLSS_Eval_Params* lastSlot;
    float slotSharp[4];           // our sharpness per slot (NGX InSharpness is deprecated in SDK 310: "Sharpness is not supported")
    int passthrough;
    int lastError;

    // Sharpen pass (runs after NGX on the output UAV): NIS sharpen-only (DLSS_SHARPEN_NIS), else RCAS fallback.
    // Scratch = SRV copy of the output, since in-place read+write is a hazard.
    int sharpener;                // DLSS_SHARPEN_* once a shader compiled
    ID3D11ComputeShader* rcasCs;  // the active shader (NIS or RCAS)
    ID3D11Buffer* rcasCb;         // 256 B dynamic cbuffer (NISConfig is 256 B aligned; RCAS uses 16 B)
    ID3D11SamplerState* sampler;  // linear clamp, NIS samples uv
    ID3D11Texture2D* scratch;
    ID3D11ShaderResourceView* scratchSrv;
    ID3D11UnorderedAccessView* outUav;
    ID3D11Resource* outUavRes;    // the resource outUav was built for (released on DLSS_EV_RELEASE, before Unity frees RTs)
    unsigned scratchW, scratchH;
    DXGI_FORMAT scratchFmt;
    int rcasDead;                 // shader compile / view creation failed once -> pass skipped for good
} S = { DLSS_ERR_NO_DEVICE };

// AMD FidelityFX RCAS (ffx_fsr1.h FsrRcasF, MIT), written from the public formula. Denominators are epsilon-guarded
// instead of relying on rcp()->inf + NaN-dropping min/max. FSR_RCAS_DENOISE on. Alpha passes through.
static const char kRcasHlsl[] =
"Texture2D<float4> src : register(t0);\n"
"RWTexture2D<float4> dst : register(u0);\n"
"cbuffer C : register(b0) { float con; float pad0; uint W; uint H; };\n"
"float3 L(int2 p) { p = clamp(p, int2(0,0), int2(int(W)-1, int(H)-1)); return src.Load(int3(p,0)).rgb; }\n"
"[numthreads(8,8,1)]\n"
"void main(uint3 id : SV_DispatchThreadID) {\n"
"  if (id.x >= W || id.y >= H) return;\n"
"  int2 p = int2(id.xy);\n"
"  float3 b = L(p+int2(0,-1)), d = L(p+int2(-1,0)), e = L(p), f = L(p+int2(1,0)), h = L(p+int2(0,1));\n"
"  float bL = b.b*0.5+(b.r*0.5+b.g), dL = d.b*0.5+(d.r*0.5+d.g), eL = e.b*0.5+(e.r*0.5+e.g);\n"
"  float fL = f.b*0.5+(f.r*0.5+f.g), hL = h.b*0.5+(h.r*0.5+h.g);\n"
"  float mxL = max(max(max(bL,dL),max(eL,fL)),hL), mnL = min(min(min(bL,dL),min(eL,fL)),hL);\n"
"  float nz = 0.25*(bL+dL+fL+hL) - eL;\n"
"  nz = saturate(abs(nz) / max(mxL - mnL, 1e-5));\n"
"  nz = -0.5*nz + 1.0;\n"
"  float3 mn4 = min(min(b,d),min(f,h)), mx4 = max(max(b,d),max(f,h));\n"
"  float3 hitMin = mn4 / max(4.0*mx4, 1e-5);\n"
"  float3 hitMax = (1.0 - mx4) / min(4.0*mn4 - 4.0, -1e-5);\n"
"  float3 lobeRGB = max(-hitMin, hitMax);\n"
"  float lobe = max(-0.1875, min(max(max(lobeRGB.r,lobeRGB.g),lobeRGB.b), 0.0)) * con;\n"
"  lobe *= nz;\n"
"  float3 c = (lobe*(b+d+f+h) + e) / (4.0*lobe + 1.0);\n"
"  dst[id.xy] = float4(c, src.Load(int3(p,0)).a);\n"
"}\n";

// NIS sharpen-only: the NIS_Main.hlsl example's bindings + NVSharpen entry. Block/group sizes = NISOptimizer(isUpscaling=false,
// NVIDIA_Generic) in NIS_Config.h (32 x 32, 128 threads). NIS_HDR_MODE 0: the DLSS output is display-referred LDR.
static const char kNisPreamble[] =
"#define NIS_HLSL 1\n#define NIS_SCALER 0\n#define NIS_HDR_MODE 0\n"
"#define NIS_BLOCK_WIDTH 32\n#define NIS_BLOCK_HEIGHT 32\n#define NIS_THREAD_GROUP_SIZE 128\n"
"cbuffer cb : register(b0) {\n"
" float kDetectRatio; float kDetectThres; float kMinContrastRatio; float kRatioNorm;\n"
" float kContrastBoost; float kEps; float kSharpStartY; float kSharpScaleY;\n"
" float kSharpStrengthMin; float kSharpStrengthScale; float kSharpLimitMin; float kSharpLimitScale;\n"
" float kScaleX; float kScaleY; float kDstNormX; float kDstNormY; float kSrcNormX; float kSrcNormY;\n"
" uint kInputViewportOriginX; uint kInputViewportOriginY; uint kInputViewportWidth; uint kInputViewportHeight;\n"
" uint kOutputViewportOriginX; uint kOutputViewportOriginY; uint kOutputViewportWidth; uint kOutputViewportHeight;\n"
" float reserved0; float reserved1; };\n"
"SamplerState samplerLinearClamp : register(s0);\n"
"Texture2D in_texture : register(t0);\n"
"RWTexture2D<float4> out_texture : register(u0);\n";
static const char kNisMain[] =
"\n[numthreads(NIS_THREAD_GROUP_SIZE, 1, 1)]\n"
"void main(uint3 blockIdx : SV_GroupID, uint3 threadIdx : SV_GroupThreadID) { NVSharpen(blockIdx.xy, threadIdx.x); }\n";

static void RcasFail(void) { S.rcasDead = 1; S.lastError = DLSS_ERR_SHARPEN; }

static ID3D11ComputeShader* CompileCs(const char* src, size_t len, const char* name)
{
    ID3DBlob* code = NULL; ID3DBlob* err = NULL; ID3D11ComputeShader* cs = NULL;
    HRESULT hr = D3DCompile(src, len, name, NULL, NULL, "main", "cs_5_0", D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, &code, &err);
    if (err) err->Release();
    if (FAILED(hr) || !code) return NULL;
    hr = S.device->CreateComputeShader(code->GetBufferPointer(), code->GetBufferSize(), NULL, &cs);
    code->Release();
    return SUCCEEDED(hr) ? cs : NULL;
}

static ID3D11ComputeShader* CompileNis(void)
{
    size_t a = sizeof(kNisPreamble) - 1, b = strlen((const char*)kNisScalerHlsl), c = sizeof(kNisMain) - 1;
    char* src = (char*)malloc(a + b + c + 1);
    if (!src) return NULL;
    memcpy(src, kNisPreamble, a); memcpy(src + a, kNisScalerHlsl, b); memcpy(src + a + b, kNisMain, c + 1);
    ID3D11ComputeShader* cs = CompileCs(src, a + b + c, "nis_sharpen");
    free(src);
    return cs;
}

static void RcasReleaseViews(void)
{
    if (S.outUav) { S.outUav->Release(); S.outUav = NULL; } S.outUavRes = NULL;
    if (S.scratchSrv) { S.scratchSrv->Release(); S.scratchSrv = NULL; }
    if (S.scratch) { S.scratch->Release(); S.scratch = NULL; }
    S.scratchW = S.scratchH = 0;
}

static int RcasEnsureShader(void)
{
    if (S.rcasCs) return 1;
    S.rcasCs = CompileNis();
    S.sharpener = S.rcasCs ? DLSS_SHARPEN_NIS : 0;
    if (!S.rcasCs) { S.rcasCs = CompileCs(kRcasHlsl, sizeof(kRcasHlsl) - 1, "rcas"); if (S.rcasCs) S.sharpener = DLSS_SHARPEN_RCAS; }
    if (!S.rcasCs) { RcasFail(); return 0; }
    D3D11_BUFFER_DESC bd = {};
    bd.ByteWidth = 256; bd.Usage = D3D11_USAGE_DYNAMIC; bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER; bd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    if (FAILED(S.device->CreateBuffer(&bd, NULL, &S.rcasCb))) { RcasFail(); return 0; }
    D3D11_SAMPLER_DESC sd = {};
    sd.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
    sd.AddressU = sd.AddressV = sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
    sd.MaxLOD = D3D11_FLOAT32_MAX;
    if (FAILED(S.device->CreateSamplerState(&sd, &S.sampler))) { RcasFail(); return 0; }
    return 1;
}

// sharpness 0..1 (slider/100). NIS: passed straight to NVSharpenUpdateConfig (its own 0..1 slider). RCAS fallback mapping
// = the FSR1 sample's: attenuation stops = 2*(1-s), con = exp2(-stops), so s=1 -> con=1. s=0 -> pass skipped by the caller.
static void DoSharpen(ID3D11DeviceContext* ctx, ID3D11Resource* output, float sharpness)
{
    if (S.rcasDead || !output || !S.device) return;
    if (!RcasEnsureShader()) return;

    ID3D11Texture2D* tex = NULL;
    if (FAILED(output->QueryInterface(__uuidof(ID3D11Texture2D), (void**)&tex)) || !tex) { RcasFail(); return; }
    D3D11_TEXTURE2D_DESC od = {}; tex->GetDesc(&od);
    tex->Release();
    DXGI_FORMAT viewFmt = od.Format;
    if (viewFmt == DXGI_FORMAT_R8G8B8A8_TYPELESS) viewFmt = DXGI_FORMAT_R8G8B8A8_UNORM;
    else if (viewFmt == DXGI_FORMAT_B8G8R8A8_TYPELESS) viewFmt = DXGI_FORMAT_B8G8R8A8_UNORM;
    else if (viewFmt == DXGI_FORMAT_R16G16B16A16_TYPELESS) viewFmt = DXGI_FORMAT_R16G16B16A16_FLOAT;

    if (!S.scratch || S.scratchW != od.Width || S.scratchH != od.Height || S.scratchFmt != od.Format) {
        RcasReleaseViews();
        D3D11_TEXTURE2D_DESC sd = od;
        sd.BindFlags = D3D11_BIND_SHADER_RESOURCE; sd.MiscFlags = 0; sd.Usage = D3D11_USAGE_DEFAULT; sd.CPUAccessFlags = 0;
        if (FAILED(S.device->CreateTexture2D(&sd, NULL, &S.scratch))) { RcasFail(); return; }
        D3D11_SHADER_RESOURCE_VIEW_DESC sv = {};
        sv.Format = viewFmt; sv.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D; sv.Texture2D.MipLevels = 1;
        if (FAILED(S.device->CreateShaderResourceView(S.scratch, &sv, &S.scratchSrv))) { RcasFail(); return; }
        S.scratchW = od.Width; S.scratchH = od.Height; S.scratchFmt = od.Format;
    }
    if (S.outUavRes != output) {
        if (S.outUav) { S.outUav->Release(); S.outUav = NULL; }
        D3D11_UNORDERED_ACCESS_VIEW_DESC uv = {};
        uv.Format = viewFmt; uv.ViewDimension = D3D11_UAV_DIMENSION_TEXTURE2D;
        if (FAILED(S.device->CreateUnorderedAccessView(output, &uv, &S.outUav))) { RcasFail(); return; }
        S.outUavRes = output;
    }

    ctx->CopyResource(S.scratch, output);
    D3D11_MAPPED_SUBRESOURCE m = {};
    if (SUCCEEDED(ctx->Map(S.rcasCb, 0, D3D11_MAP_WRITE_DISCARD, 0, &m))) {
        if (S.sharpener == DLSS_SHARPEN_NIS) {
            NISConfig cfg = {};
            NVSharpenUpdateConfig(cfg, sharpness, 0, 0, od.Width, od.Height, od.Width, od.Height, 0, 0, NISHDRMode::None);
            memcpy(m.pData, &cfg, sizeof(cfg));
        } else {
            float* fp = (float*)m.pData; unsigned* up = (unsigned*)m.pData;
            fp[0] = exp2f(-2.0f * (1.0f - sharpness)); fp[1] = 0.0f; up[2] = od.Width; up[3] = od.Height;
        }
        ctx->Unmap(S.rcasCb, 0);
    }
    ctx->CSSetShader(S.rcasCs, NULL, 0);
    ctx->CSSetConstantBuffers(0, 1, &S.rcasCb);
    ctx->CSSetSamplers(0, 1, &S.sampler);
    ctx->CSSetShaderResources(0, 1, &S.scratchSrv);
    ctx->CSSetUnorderedAccessViews(0, 1, &S.outUav, NULL);
    if (S.sharpener == DLSS_SHARPEN_NIS) ctx->Dispatch((od.Width + 31) / 32, (od.Height + 31) / 32, 1);
    else ctx->Dispatch((od.Width + 7) / 8, (od.Height + 7) / 8, 1);
    // Unbind: the output must not stay bound as a UAV when Unity samples it for the present blit.
    ID3D11UnorderedAccessView* nullUav = NULL; ID3D11ShaderResourceView* nullSrv = NULL; ID3D11Buffer* nullCb = NULL; ID3D11SamplerState* nullSs = NULL;
    ctx->CSSetUnorderedAccessViews(0, 1, &nullUav, NULL);
    ctx->CSSetShaderResources(0, 1, &nullSrv);
    ctx->CSSetConstantBuffers(0, 1, &nullCb);
    ctx->CSSetSamplers(0, 1, &nullSs);
    ctx->CSSetShader(NULL, NULL, 0);
}

static NVSDK_NGX_PerfQuality_Value ToNgxQuality(int q)
{
    switch (q) {
    case DLSS_Q_DLAA:              return NVSDK_NGX_PerfQuality_Value_DLAA;
    case DLSS_Q_BALANCED:          return NVSDK_NGX_PerfQuality_Value_Balanced;
    case DLSS_Q_PERFORMANCE:       return NVSDK_NGX_PerfQuality_Value_MaxPerf;
    case DLSS_Q_ULTRA_PERFORMANCE: return NVSDK_NGX_PerfQuality_Value_UltraPerformance;
    default:                       return NVSDK_NGX_PerfQuality_Value_MaxQuality;
    }
}

int __cdecl Dlss_Init(void* anyD3D11Resource, const wchar_t* dllDir, const wchar_t* logDir)
{
    if (S.ngxInitialized) return S.initCode;
    if (!anyD3D11Resource) return S.initCode = DLSS_ERR_NO_DEVICE;

    ID3D11Resource* res = NULL;
    if (FAILED(((IUnknown*)anyD3D11Resource)->QueryInterface(__uuidof(ID3D11Resource), (void**)&res)) || !res)
        return S.initCode = DLSS_ERR_NO_DEVICE;
    res->GetDevice(&S.device);
    res->Release();
    if (!S.device) return S.initCode = DLSS_ERR_NO_DEVICE;

    if (dllDir) wcsncpy_s(S.dllDir, dllDir, _TRUNCATE);
    const wchar_t* paths[1] = { S.dllDir };
    NVSDK_NGX_FeatureCommonInfo common = {};
    common.PathListInfo.Path = paths;
    common.PathListInfo.Length = dllDir ? 1 : 0;
    common.LoggingInfo.MinimumLoggingLevel = NVSDK_NGX_LOGGING_LEVEL_ON;

    NVSDK_NGX_Result r = NVSDK_NGX_D3D11_Init_with_ProjectID(kProjectId, NVSDK_NGX_ENGINE_TYPE_UNITY, kEngineVersion,
                                                             logDir ? logDir : L".", S.device, &common, NVSDK_NGX_Version_API);
    if (NVSDK_NGX_FAILED(r)) { S.lastCreate = r; S.device->Release(); S.device = NULL; return S.initCode = DLSS_ERR_INIT_FAILED; }
    S.ngxInitialized = 1;

    r = NVSDK_NGX_D3D11_GetCapabilityParameters(&S.params);
    if (NVSDK_NGX_FAILED(r) || !S.params) { S.lastCreate = r; return S.initCode = DLSS_ERR_INIT_FAILED; }

    int available = 0;
    NVSDK_NGX_Parameter_GetI(S.params, NVSDK_NGX_Parameter_SuperSampling_Available, &available);
    NVSDK_NGX_Parameter_GetI(S.params, NVSDK_NGX_Parameter_SuperSampling_NeedsUpdatedDriver, &S.needsDriver);
    NVSDK_NGX_Parameter_GetUI(S.params, NVSDK_NGX_Parameter_SuperSampling_MinDriverVersionMajor, &S.minDriverMajor);
    NVSDK_NGX_Parameter_GetUI(S.params, NVSDK_NGX_Parameter_SuperSampling_MinDriverVersionMinor, &S.minDriverMinor);

    if (S.needsDriver) return S.initCode = DLSS_ERR_NEEDS_DRIVER;
    if (!available) return S.initCode = DLSS_ERR_NOT_AVAILABLE;
    return S.initCode = DLSS_OK;
}

int __cdecl Dlss_GetOptimal(unsigned outW, unsigned outH, int quality,
                            unsigned* renderW, unsigned* renderH,
                            unsigned* minW, unsigned* minH, unsigned* maxW, unsigned* maxH)
{
    if (!S.params) return NVSDK_NGX_Result_FAIL_NotInitialized;
    unsigned w = 0, h = 0, mnw = 0, mnh = 0, mxw = 0, mxh = 0; float sharp = 0;
    NVSDK_NGX_Result r = NGX_DLSS_GET_OPTIMAL_SETTINGS(S.params, outW, outH, ToNgxQuality(quality),
                                                       &w, &h, &mxw, &mxh, &mnw, &mnh, &sharp);
    if (renderW) *renderW = w; if (renderH) *renderH = h;
    if (minW) *minW = mnw;     if (minH) *minH = mnh;
    if (maxW) *maxW = mxw;     if (maxH) *maxH = mxh;
    return r;
}

void __cdecl Dlss_SetCreateParams(unsigned w, unsigned h, unsigned outW, unsigned outH, int quality, int flags)
{
    memset(&S.create, 0, sizeof(S.create));
    S.create.Feature.InWidth = w;
    S.create.Feature.InHeight = h;
    S.create.Feature.InTargetWidth = outW;
    S.create.Feature.InTargetHeight = outH;
    S.create.Feature.InPerfQualityValue = ToNgxQuality(quality);
    S.quality = quality;
    int f = 0;
    if (flags & DLSS_F_HDR)            f |= NVSDK_NGX_DLSS_Feature_Flags_IsHDR;
    if (flags & DLSS_F_DEPTH_INVERTED) f |= NVSDK_NGX_DLSS_Feature_Flags_DepthInverted;
    if (flags & DLSS_F_MV_LOW_RES)     f |= NVSDK_NGX_DLSS_Feature_Flags_MVLowRes;
    if (flags & DLSS_F_MV_JITTERED)    f |= NVSDK_NGX_DLSS_Feature_Flags_MVJittered;
    if (flags & DLSS_F_AUTO_EXPOSURE)  f |= NVSDK_NGX_DLSS_Feature_Flags_AutoExposure;
    S.create.InFeatureCreateFlags = f;
}

void* __cdecl Dlss_GetFrameSlot(void)
{
    return &S.slots[S.slotIdx++ & 3u];
}

void __cdecl Dlss_SetFrame(void* slot, void* color, void* depth, void* mv, void* output,
                           float jitterX, float jitterY, float mvScaleX, float mvScaleY,
                           int reset, float dtMs, unsigned renderW, unsigned renderH,
                           float preExposure, float sharpness)
{
    NVSDK_NGX_D3D11_DLSS_Eval_Params* p = (NVSDK_NGX_D3D11_DLSS_Eval_Params*)slot;
    if (!p) return;
    S.lastSlot = p;
    memset(p, 0, sizeof(*p));
    ptrdiff_t idx = p - S.slots;
    if (idx >= 0 && idx < 4) S.slotSharp[idx] = sharpness < 0 ? 0 : sharpness > 1 ? 1 : sharpness;
    p->Feature.pInColor = (ID3D11Resource*)color;
    p->Feature.pInOutput = (ID3D11Resource*)output;
    p->Feature.InSharpness = 0;   // deprecated in SDK 310 ("Sharpness is not supported"); our RCAS pass uses slotSharp instead
    p->pInDepth = (ID3D11Resource*)depth;
    p->pInMotionVectors = (ID3D11Resource*)mv;
    p->InJitterOffsetX = jitterX;
    p->InJitterOffsetY = jitterY;
    p->InRenderSubrectDimensions.Width = renderW;
    p->InRenderSubrectDimensions.Height = renderH;
    p->InReset = reset;
    p->InMVScaleX = mvScaleX;
    p->InMVScaleY = mvScaleY;
    p->InPreExposure = preExposure;
    p->InFrameTimeDeltaInMsec = dtMs;
}

static void DoCreate(void)
{
    if (!S.params || !S.device) { S.lastCreate = NVSDK_NGX_Result_FAIL_NotInitialized; return; }
    if (S.feature) { NVSDK_NGX_D3D11_ReleaseFeature(S.feature); S.feature = NULL; }
    if (!S.create.Feature.InWidth || !S.create.Feature.InTargetWidth) { S.lastCreate = NVSDK_NGX_Result_FAIL_InvalidParameter; return; }

    // Render preset hints: K (transformer) for DLAA/Q/B, M for Perf, L for UltraPerf (header defaults per mode).
    NVSDK_NGX_Parameter_SetUI(S.params, NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_DLAA, NVSDK_NGX_DLSS_Hint_Render_Preset_K);
    NVSDK_NGX_Parameter_SetUI(S.params, NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Quality, NVSDK_NGX_DLSS_Hint_Render_Preset_K);
    NVSDK_NGX_Parameter_SetUI(S.params, NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Balanced, NVSDK_NGX_DLSS_Hint_Render_Preset_K);
    NVSDK_NGX_Parameter_SetUI(S.params, NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Performance, NVSDK_NGX_DLSS_Hint_Render_Preset_M);
    NVSDK_NGX_Parameter_SetUI(S.params, NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_UltraPerformance, NVSDK_NGX_DLSS_Hint_Render_Preset_L);

    ID3D11DeviceContext* ctx = NULL;
    S.device->GetImmediateContext(&ctx);
    if (!ctx) { S.lastCreate = NVSDK_NGX_Result_FAIL_PlatformError; return; }
    S.lastCreate = NGX_D3D11_CREATE_DLSS_EXT(ctx, &S.feature, S.params, &S.create);
    ctx->Release();
    if (NVSDK_NGX_FAILED(S.lastCreate)) { S.feature = NULL; S.lastError = (int)S.lastCreate; }
}

static int SameSize(ID3D11Resource* a, ID3D11Resource* b)
{
    ID3D11Texture2D* ta = NULL; ID3D11Texture2D* tb = NULL;
    D3D11_TEXTURE2D_DESC da = {}, db = {};
    if (FAILED(a->QueryInterface(__uuidof(ID3D11Texture2D), (void**)&ta)) || !ta) return 0;
    if (FAILED(b->QueryInterface(__uuidof(ID3D11Texture2D), (void**)&tb)) || !tb) { ta->Release(); return 0; }
    ta->GetDesc(&da); tb->GetDesc(&db);
    ta->Release(); tb->Release();
    return da.Width == db.Width && da.Height == db.Height;
}

static void DoEvaluate(NVSDK_NGX_D3D11_DLSS_Eval_Params* p)
{
    if (!p) p = S.lastSlot;
    if (!p) { S.lastEval = NVSDK_NGX_Result_FAIL_MissingInput; S.lastError = (int)S.lastEval; return; }
    if (!S.device) { S.lastEval = NVSDK_NGX_Result_FAIL_NotInitialized; S.lastError = (int)S.lastEval; return; }
    if (!p->Feature.pInColor || !p->Feature.pInOutput || (!S.passthrough && (!p->pInDepth || !p->pInMotionVectors))) {
        S.lastEval = NVSDK_NGX_Result_FAIL_MissingInput; S.lastError = (int)S.lastEval; return;
    }
    ID3D11DeviceContext* ctx = NULL;
    S.device->GetImmediateContext(&ctx);
    if (!ctx) { S.lastEval = NVSDK_NGX_Result_FAIL_PlatformError; S.lastError = DLSS_ERR_NO_CONTEXT; return; }
    if (S.passthrough) {
        if (SameSize(p->Feature.pInColor, p->Feature.pInOutput)) { ctx->CopyResource(p->Feature.pInOutput, p->Feature.pInColor); S.lastEval = NVSDK_NGX_Result_Success; }
        else { S.lastEval = NVSDK_NGX_Result_FAIL_InvalidParameter; S.lastError = DLSS_ERR_PASSTHROUGH_SIZE; }
    } else if (!S.feature || !S.params) {
        S.lastEval = NVSDK_NGX_Result_FAIL_FeatureNotFound; S.lastError = (int)S.lastEval;
    } else {
        S.lastEval = NGX_D3D11_EVALUATE_DLSS_EXT(ctx, S.feature, S.params, p);
        if (NVSDK_NGX_FAILED(S.lastEval)) S.lastError = (int)S.lastEval;
        else {
            ptrdiff_t idx = p - S.slots;
            float sharp = (idx >= 0 && idx < 4) ? S.slotSharp[idx] : 0.0f;
            if (sharp > 0.0f) DoSharpen(ctx, p->Feature.pInOutput, sharp);   // not in passthrough: no DLSS_EV_RELEASE there to drop the cached UAV
        }
    }
    ctx->Release();
}

static void DoRelease(void)
{
    RcasReleaseViews();   // outUav refs a Unity RT the driver frees two frames after this event
    if (!S.feature) return;
    NVSDK_NGX_D3D11_ReleaseFeature(S.feature);
    S.feature = NULL;
}

static void __stdcall OnRenderEventAndData(int eventId, void* data)
{
    switch (eventId) {
    case DLSS_EV_CREATE:   DoCreate();   break;
    case DLSS_EV_EVALUATE: DoEvaluate((NVSDK_NGX_D3D11_DLSS_Eval_Params*)data); break;
    case DLSS_EV_RELEASE:  DoRelease();  break;
    default: break;
    }
}

static void __stdcall OnRenderEvent(int eventId) { OnRenderEventAndData(eventId, NULL); }

void* __cdecl Dlss_GetRenderEventFunc(void)        { return (void*)&OnRenderEvent; }
void* __cdecl Dlss_GetRenderEventAndDataFunc(void) { return (void*)&OnRenderEventAndData; }

int __cdecl Dlss_Passthrough(int on) { int prev = S.passthrough; S.passthrough = on ? 1 : 0; return prev; }
int __cdecl Dlss_LastError(void)     { return S.lastError; }
int __cdecl Dlss_Sharpener(void)     { return S.rcasDead ? DLSS_SHARPEN_FAILED : S.sharpener; }

int __cdecl Dlss_Status(int* lastCreateResult, int* lastEvalResult, int* featureAlive)
{
    if (lastCreateResult) *lastCreateResult = (int)S.lastCreate;
    if (lastEvalResult) *lastEvalResult = (int)S.lastEval;
    if (featureAlive) *featureAlive = S.feature ? 1 : 0;
    return S.initCode;
}

const char* __cdecl Dlss_ResultString(int ngxResult)
{
    static char buf[256];
    const wchar_t* w = GetNGXResultAsString((NVSDK_NGX_Result)ngxResult);
    if (!w) return "NVSDK_NGX_Result_Unknown";
    size_t n = 0;
    wcstombs_s(&n, buf, sizeof(buf), w, _TRUNCATE);
    return buf;
}

void __cdecl Dlss_ReleaseNow(void) { DoRelease(); }

void __cdecl Dlss_Shutdown(void)
{
    DoRelease();
    if (S.rcasCb) { S.rcasCb->Release(); S.rcasCb = NULL; }
    if (S.rcasCs) { S.rcasCs->Release(); S.rcasCs = NULL; }
    if (S.sampler) { S.sampler->Release(); S.sampler = NULL; }
    S.rcasDead = 0; S.sharpener = 0;
    if (S.params) { NVSDK_NGX_D3D11_DestroyParameters(S.params); S.params = NULL; }
    if (S.ngxInitialized) { NVSDK_NGX_D3D11_Shutdown1(S.device); S.ngxInitialized = 0; }
    if (S.device) { S.device->Release(); S.device = NULL; }
    S.initCode = DLSS_ERR_NO_DEVICE;
}
