// Sharpen.cpp - HLSL sources + compile + constant packing for the post-DLSS sharpen pass.
#include "Sharpen.h"
#include "RenderforgeNative.h"

#include <d3dcompiler.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

#include "nis/NIS_Config.h"     // NVIDIA Image Scaling SDK 1.0.3 (MIT): NISConfig + NVSharpenUpdateConfig
#include "nis_scaler_hlsl.h"    // generated by CMake from nis/NIS_Scaler.h: kNisScalerHlsl[] (NUL-terminated)

// AMD FidelityFX RCAS (ffx_fsr1.h FsrRcasF, MIT), written from the public formula. Denominators are epsilon-guarded
// instead of relying on rcp()->inf + NaN-dropping min/max. FSR_RCAS_DENOISE on. Alpha passes through.
static const char kRcasHlsl[] =
"Texture2D<float4> src : register(t0);\n"
"RWTexture2D<float4> dst : register(u0);\n"
"cbuffer C : register(b0) { float con; float pad0; uint W; uint H; };\n"
"float3 L(int2 p) { p = clamp(p, int2(0,0), int2(int(W)-1, int(H)-1)); return src.Load(int3(p,0)).rgb; }\n"
"[numthreads(8,8,1)]\n"
"void main(uint3 id : SV_DispatchThreadID) {\n"
"  if (id.x >= W || id.y >= H) return;\n"
"  int2 p = int2(id.xy);\n"
"  float3 b = L(p+int2(0,-1)), d = L(p+int2(-1,0)), e = L(p), f = L(p+int2(1,0)), h = L(p+int2(0,1));\n"
"  float bL = b.b*0.5+(b.r*0.5+b.g), dL = d.b*0.5+(d.r*0.5+d.g), eL = e.b*0.5+(e.r*0.5+e.g);\n"
"  float fL = f.b*0.5+(f.r*0.5+f.g), hL = h.b*0.5+(h.r*0.5+h.g);\n"
"  float mxL = max(max(max(bL,dL),max(eL,fL)),hL), mnL = min(min(min(bL,dL),min(eL,fL)),hL);\n"
"  float nz = 0.25*(bL+dL+fL+hL) - eL;\n"
"  nz = saturate(abs(nz) / max(mxL - mnL, 1e-5));\n"
"  nz = -0.5*nz + 1.0;\n"
"  float3 mn4 = min(min(b,d),min(f,h)), mx4 = max(max(b,d),max(f,h));\n"
"  float3 hitMin = mn4 / max(4.0*mx4, 1e-5);\n"
"  float3 hitMax = (1.0 - mx4) / min(4.0*mn4 - 4.0, -1e-5);\n"
"  float3 lobeRGB = max(-hitMin, hitMax);\n"
"  float lobe = max(-0.1875, min(max(max(lobeRGB.r,lobeRGB.g),lobeRGB.b), 0.0)) * con;\n"
"  lobe *= nz;\n"
"  float3 c = (lobe*(b+d+f+h) + e) / (4.0*lobe + 1.0);\n"
"  dst[id.xy] = float4(c, src.Load(int3(p,0)).a);\n"
"}\n";

// NIS sharpen-only: the NIS_Main.hlsl example's bindings + NVSharpen entry. Block/group sizes = NISOptimizer(isUpscaling=false,
// NVIDIA_Generic) in NIS_Config.h (32 x 32, 128 threads). NIS_HDR_MODE 0: the DLSS output is display-referred LDR.
static const char kNisPreamble[] =
"#define NIS_HLSL 1\n#define NIS_SCALER 0\n#define NIS_HDR_MODE 0\n"
"#define NIS_BLOCK_WIDTH 32\n#define NIS_BLOCK_HEIGHT 32\n#define NIS_THREAD_GROUP_SIZE 128\n"
"cbuffer cb : register(b0) {\n"
" float kDetectRatio; float kDetectThres; float kMinContrastRatio; float kRatioNorm;\n"
" float kContrastBoost; float kEps; float kSharpStartY; float kSharpScaleY;\n"
" float kSharpStrengthMin; float kSharpStrengthScale; float kSharpLimitMin; float kSharpLimitScale;\n"
" float kScaleX; float kScaleY; float kDstNormX; float kDstNormY; float kSrcNormX; float kSrcNormY;\n"
" uint kInputViewportOriginX; uint kInputViewportOriginY; uint kInputViewportWidth; uint kInputViewportHeight;\n"
" uint kOutputViewportOriginX; uint kOutputViewportOriginY; uint kOutputViewportWidth; uint kOutputViewportHeight;\n"
" float reserved0; float reserved1; };\n"
"SamplerState samplerLinearClamp : register(s0);\n"
"Texture2D in_texture : register(t0);\n"
"RWTexture2D<float4> out_texture : register(u0);\n";
static const char kNisMain[] =
"\n[numthreads(NIS_THREAD_GROUP_SIZE, 1, 1)]\n"
"void main(uint3 blockIdx : SV_GroupID, uint3 threadIdx : SV_GroupThreadID) { NVSharpen(blockIdx.xy, threadIdx.x); }\n";

static ID3DBlob* Compile(const char* src, size_t len, const char* name)
{
    ID3DBlob* code = NULL; ID3DBlob* err = NULL;
    HRESULT hr = D3DCompile(src, len, name, NULL, NULL, "main", "cs_5_0", D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, &code, &err);
    if (err) err->Release();
    if (FAILED(hr)) { if (code) { code->Release(); code = NULL; } }
    return code;
}

static ID3DBlob* CompileNis(void)
{
    size_t a = sizeof(kNisPreamble) - 1, b = strlen((const char*)kNisScalerHlsl), c = sizeof(kNisMain) - 1;
    char* src = (char*)malloc(a + b + c + 1);
    if (!src) return NULL;
    memcpy(src, kNisPreamble, a); memcpy(src + a, kNisScalerHlsl, b); memcpy(src + a + b, kNisMain, c + 1);
    ID3DBlob* blob = Compile(src, a + b + c, "nis_sharpen");
    free(src);
    return blob;
}

ID3DBlob* CompileSharpenBlob(int* outKind)
{
    ID3DBlob* blob = CompileNis();
    if (blob) { if (outKind) *outKind = DLSS_SHARPEN_NIS; return blob; }
    blob = Compile(kRcasHlsl, sizeof(kRcasHlsl) - 1, "rcas");
    if (blob && outKind) *outKind = DLSS_SHARPEN_RCAS;
    return blob;
}

void FillSharpenConstants(void* dst256, int kind, float sharpness, unsigned w, unsigned h)
{
    memset(dst256, 0, 256);
    if (kind == DLSS_SHARPEN_NIS) {
        NISConfig cfg = {};
        NVSharpenUpdateConfig(cfg, sharpness, 0, 0, w, h, w, h, 0, 0, NISHDRMode::None);
        memcpy(dst256, &cfg, sizeof(cfg));
    } else {
        // RCAS mapping = the FSR1 sample's: attenuation stops = 2*(1-s), con = exp2(-stops), so s=1 -> con=1.
        float* fp = (float*)dst256; unsigned* up = (unsigned*)dst256;
        fp[0] = exp2f(-2.0f * (1.0f - sharpness)); fp[1] = 0.0f; up[2] = w; up[3] = h;
    }
}

DXGI_FORMAT SharpenViewFormat(DXGI_FORMAT fmt)
{
    switch (fmt) {
    case DXGI_FORMAT_R8G8B8A8_TYPELESS:     return DXGI_FORMAT_R8G8B8A8_UNORM;
    case DXGI_FORMAT_B8G8R8A8_TYPELESS:     return DXGI_FORMAT_B8G8R8A8_UNORM;
    case DXGI_FORMAT_R16G16B16A16_TYPELESS: return DXGI_FORMAT_R16G16B16A16_FLOAT;
    default:                                return fmt;
    }
}
