// Sharpen.cpp - precompiled post-pass bytecode lookup + constant packing for the post-DLSS sharpen pass.
// The HLSL lives in SharpenHlsl.h and is compiled at BUILD time (shadergen/rf_shadergen.cpp -> sharpen_dxbc.h).
#include "Sharpen.h"
#include "RenderforgeNative.h"

#include <d3dcompiler.h>
#include <math.h>
#include <string.h>

#include "nis/NIS_Config.h"     // NVIDIA Image Scaling SDK 1.0.3 (MIT): NISConfig + NVSharpenUpdateConfig
#include "sharpen_dxbc.h"       // generated by rf_shadergen: kCsNisLdr / kCsNisHdr / kCsGrade (DXBC cs_5_0)

const void* SharpenBytecode(bool hdr, bool colorGrade, size_t* size, int* outKind)
{
    const unsigned char* code; size_t n; int kind;
    if (colorGrade)  { code = kCsGrade;  n = sizeof(kCsGrade);  kind = DLSS_SHARPEN_RCAS; }   // hdr rides in the cbuffer (styleLinear)
    else if (hdr)    { code = kCsNisHdr; n = sizeof(kCsNisHdr); kind = DLSS_SHARPEN_NIS; }
    else             { code = kCsNisLdr; n = sizeof(kCsNisLdr); kind = DLSS_SHARPEN_NIS; }
    if (size) *size = n;
    if (outKind) *outKind = kind;
    return code;
}

ID3DBlob* CompileSharpenBlob(int* outKind, bool hdr, bool colorGrade)
{
    size_t n = 0; int kind = 0;
    const void* code = SharpenBytecode(hdr, colorGrade, &n, &kind);
    ID3DBlob* blob = NULL;
    if (FAILED(D3DCreateBlob(n, &blob)) || !blob) return NULL;
    memcpy(blob->GetBufferPointer(), code, n);
    if (outKind) *outKind = kind;
    return blob;
}

void FillSharpenConstants(void* dst256, int kind, float sharpness, unsigned w, unsigned h,
                          int lutPreset, float lutStrength, bool hdr, const SceneStyleParams& style,
                          int colorVision, const GradeParams& grade)
{
    memset(dst256, 0, 256);
    if (PostShaderEnabled(lutPreset, lutStrength, style, colorVision, grade)) {
        float* fp = (float*)dst256; unsigned* up = (unsigned*)dst256;
        fp[0] = sharpness; fp[1] = lutStrength; up[2] = w; up[3] = h; up[4] = (unsigned)lutPreset;
        fp[5] = exp2f(-2.0f * (1.0f - sharpness));
        up[6] = style.mode; up[7] = style.pixelSize;
        fp[8] = style.strength; up[9] = hdr ? 1u : 0u;
        up[10] = ColorVisionEnabled(colorVision) ? (unsigned)colorVision : 0u;
        // fp[11] is the cbuffer's pad0. The three float4 rows start at float index 12 (byte 48); their w
        // components stay zero from the memset above, which is what the shader's .xyz swizzle expects.
        CvMatrix d = CvCorrection(colorVision);
        for (int row = 0; row < 3; ++row)
            for (int col = 0; col < 3; ++col)
                fp[12 + row * 4 + col] = d.m[row * 3 + col];
        // Levels / Contrast / Clarity: one float4 at byte 96 (fp[24..27]), after the three matrix rows, then
        // Exposure / Brightness / Saturation / Vibrance at byte 112 (fp[28..31]). Zero = off for all eight (Grade.h),
        // so the NIS/RCAS layouts below, which never write here, are the bypass too.
        fp[24] = grade.black; fp[25] = grade.whiteDrop; fp[26] = grade.contrastDelta; fp[27] = grade.clarity;
        fp[28] = grade.exposure; fp[29] = grade.brightness; fp[30] = grade.saturationDelta; fp[31] = grade.vibrance;
    } else if (kind == DLSS_SHARPEN_NIS) {
        NISConfig cfg = {};
        NVSharpenUpdateConfig(cfg, sharpness, 0, 0, w, h, w, h, 0, 0, hdr ? NISHDRMode::Linear : NISHDRMode::None);
        memcpy(dst256, &cfg, sizeof(cfg));
    } else {
        // RCAS mapping = the FSR1 sample's: attenuation stops = 2*(1-s), con = exp2(-stops), so s=1 -> con=1.
        float* fp = (float*)dst256; unsigned* up = (unsigned*)dst256;
        fp[0] = exp2f(-2.0f * (1.0f - sharpness)); fp[1] = 0.0f; up[2] = w; up[3] = h;
    }
}

DXGI_FORMAT SharpenViewFormat(DXGI_FORMAT fmt)
{
    switch (fmt) {
    case DXGI_FORMAT_R8G8B8A8_TYPELESS:
    case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:   return DXGI_FORMAT_R8G8B8A8_UNORM;   // sRGB has no UAV; view as UNORM (raw bytes)
    case DXGI_FORMAT_B8G8R8A8_TYPELESS:
    case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB:   return DXGI_FORMAT_B8G8R8A8_UNORM;
    case DXGI_FORMAT_R16G16B16A16_TYPELESS: return DXGI_FORMAT_R16G16B16A16_FLOAT;
    default:                                return fmt;
    }
}
